linters:
  disable:
    - wrapcheck
    - tagliatelle
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - forbidigo
    - gochecknoinits

  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  varnamelen:
    min-name-length: 2
#   exhaustruct:
#     exclude:
#       - 'cli\.*Flag'
#       - 'cli\.Command'
#       - 'cli\.App'