# https://taskfile.dev

version: '3'

vars:
  PRODUCTION_WEBHOOK: https://comunidade-shallom-bot.deno.dev

dotenv: ['.env']

tasks:
  webhook:setup:
    silent: true
    cmds:
      - curl -X GET https://api.telegram.org/bot$TELEGRAM_TOKEN/setWebhook?url={{ .PRODUCTION_WEBHOOK }}/$TELEGRAM_TOKEN | jq

  poll:
    silent: true
    cmds:
      - echo "WARNING:  Note that it will delete webhook url and you'll need to repeat webhook:setup"
      - deno run --allow-env=TELEGRAM_TOKEN --allow-net=api.telegram.org ./bin/poll.ts
