# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  poll:
    silent: true
    cmds:
      - echo "WARNING:  Note that it will delete webhook url and you'll need to repeat webhook:setup"
      - deno run --allow-env=TELEGRAM_TOKEN --allow-net=api.telegram.org ./bin/poll.ts
